# Generated by Django 6.0.7 on 2026-08-09 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0004_businessconfiguration_booking_deposit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessconfiguration',
            name='services',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
