# Generated by Django 6.0.7 on 2026-08-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0005_businessconfiguration_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessconfiguration',
            name='number_of_resources',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
