# Generated by Django 6.0.7 on 2026-08-08 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_service'),
        ('bookings', '0002_initial'),
    ]

    operations = [
    ]
