# Generated by Django 6.0.7 on 2026-08-09 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_status'),
        ('services', '0002_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='services.resource'),
        ),
    ]
